package org.redfrog404.mobycraft.entity;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelChaosMonkey extends ModelBase {
	ModelRenderer Foot1;
	ModelRenderer Foot2;
	ModelRenderer Leg1;
	ModelRenderer Leg2;
	ModelRenderer TorsoMain;
	ModelRenderer LegConnection1;
	ModelRenderer LegConnection2;
	ModelRenderer TorsoFront;
	ModelRenderer ArmConnection1;
	ModelRenderer ArmConnection2;
	ModelRenderer HandPart2;
	ModelRenderer Arm2;
	ModelRenderer Hand1;
	ModelRenderer Hand2;
	ModelRenderer Neck;
	ModelRenderer Banana;
	ModelRenderer Head;
	ModelRenderer WingConnection;
	ModelRenderer WingPart1;
	ModelRenderer WingPart2;
	ModelRenderer WingPart3;
	ModelRenderer WingPart4;
	ModelRenderer WingPart5;
	ModelRenderer WingPart6;
	ModelRenderer WingPart7;
	ModelRenderer TailFront;
	ModelRenderer TailBack;
	ModelRenderer TailMiddle;
	ModelRenderer Arm1;
	ModelRenderer HandPart1;
	ModelRenderer Ear1;
	ModelRenderer Ear2;

	public ModelChaosMonkey() {
		textureWidth = 128;
		textureHeight = 64;

		Foot1 = new ModelRenderer(this, 0, 0);
		Foot1.addBox(-1F, 0F, -1F, 4, 1, 3);
		Foot1.setRotationPoint(-7F, 23F, 0F);
		Foot1.setTextureSize(128, 64);
		Foot1.mirror = true;
		setRotation(Foot1, 0F, 0F, 0F);
		Foot2 = new ModelRenderer(this, 0, 0);
		Foot2.addBox(5F, 0F, -1F, 4, 1, 3);
		Foot2.setRotationPoint(-1F, 23F, 0F);
		Foot2.setTextureSize(128, 64);
		Foot2.mirror = true;
		setRotation(Foot2, 0F, 0F, 0F);
		Leg1 = new ModelRenderer(this, 0, 4);
		Leg1.addBox(-5F, 0F, 1F, 2, 5, 2);
		Leg1.setRotationPoint(10F, 18F, -1F);
		Leg1.setTextureSize(128, 64);
		Leg1.mirror = true;
		setRotation(Leg1, 0F, 0F, 0F);
		Leg2 = new ModelRenderer(this, 0, 4);
		Leg2.addBox(-7F, 0F, 1F, 2, 5, 2);
		Leg2.setRotationPoint(0F, 18F, -1F);
		Leg2.setTextureSize(128, 64);
		Leg2.mirror = true;
		setRotation(Leg2, 0F, 0F, 0F);
		TorsoMain = new ModelRenderer(this, 38, 0);
		TorsoMain.addBox(0F, 0F, 0F, 6, 8, 1);
		TorsoMain.setRotationPoint(-3F, 11F, -2F);
		TorsoMain.setTextureSize(128, 64);
		TorsoMain.mirror = true;
		setRotation(TorsoMain, 0F, 0F, 0F);
		LegConnection1 = new ModelRenderer(this, 52, 0);
		LegConnection1.addBox(9F, 0F, 0F, 3, 2, 2);
		LegConnection1.setRotationPoint(-6F, 18F, 0F);
		LegConnection1.setTextureSize(128, 64);
		LegConnection1.mirror = true;
		setRotation(LegConnection1, 0F, 0F, 0F);
		LegConnection2 = new ModelRenderer(this, 52, 0);
		LegConnection2.addBox(0F, 0F, 0F, 3, 2, 2);
		LegConnection2.setRotationPoint(-6F, 18F, 0F);
		LegConnection2.setTextureSize(128, 64);
		LegConnection2.mirror = true;
		setRotation(LegConnection2, 0F, 0F, 0F);
		TorsoFront = new ModelRenderer(this, 14, 0);
		TorsoFront.addBox(0F, 0F, 0F, 8, 10, 4);
		TorsoFront.setRotationPoint(-4F, 10F, -1F);
		TorsoFront.setTextureSize(128, 64);
		TorsoFront.mirror = true;
		setRotation(TorsoFront, 0F, 0F, 0F);
		ArmConnection1 = new ModelRenderer(this, 0, 11);
		ArmConnection1.addBox(0F, 0F, 0F, 3, 2, 2);
		ArmConnection1.setRotationPoint(4F, 11F, 0F);
		ArmConnection1.setTextureSize(128, 64);
		ArmConnection1.mirror = true;
		setRotation(ArmConnection1, 0F, 0F, 0F);
		ArmConnection2 = new ModelRenderer(this, 0, 11);
		ArmConnection2.addBox(0F, 0F, 0F, 3, 2, 2);
		ArmConnection2.setRotationPoint(-7F, 11F, 0F);
		ArmConnection2.setTextureSize(128, 64);
		ArmConnection2.mirror = true;
		setRotation(ArmConnection2, 0F, 0F, 0F);
		HandPart2 = new ModelRenderer(this, 100, 0);
		HandPart2.addBox(0F, 0F, 0F, 2, 2, 1);
		HandPart2.setRotationPoint(-7F, 11F, -3F);
		HandPart2.setTextureSize(128, 64);
		HandPart2.mirror = true;
		setRotation(HandPart2, 0F, 0F, 0F);
		Arm2 = new ModelRenderer(this, 0, 15);
		Arm2.addBox(0F, 0F, 0F, 2, 2, 3);
		Arm2.setRotationPoint(-7F, 11F, -2F);
		Arm2.setTextureSize(128, 64);
		Arm2.mirror = true;
		setRotation(Arm2, 0F, 0F, 0F);
		Hand1 = new ModelRenderer(this, 8, 4);
		Hand1.addBox(0F, 0F, 0F, 1, 2, 1);
		Hand1.setRotationPoint(6F, 11F, -4F);
		Hand1.setTextureSize(128, 64);
		Hand1.mirror = true;
		setRotation(Hand1, 0F, 0F, 0F);
		Hand2 = new ModelRenderer(this, 8, 4);
		Hand2.addBox(0F, 0F, 0F, 1, 2, 1);
		Hand2.setRotationPoint(-7F, 11F, -4F);
		Hand2.setTextureSize(128, 64);
		Hand2.mirror = true;
		setRotation(Hand2, 0F, 0F, 0F);
		Neck = new ModelRenderer(this, 0, 21);
		Neck.addBox(0F, 0F, 0F, 2, 2, 2);
		Neck.setRotationPoint(-1F, 8F, 0F);
		Neck.setTextureSize(128, 64);
		Neck.mirror = true;
		setRotation(Neck, 0F, 0F, 0F);
		Banana = new ModelRenderer(this, 62, 0);
		Banana.addBox(0F, 0F, 0F, 1, 4, 1);
		Banana.setRotationPoint(-6F, 10F, -4F);
		Banana.setTextureSize(128, 64);
		Banana.mirror = true;
		setRotation(Banana, 0F, 0F, 0F);
		Head = new ModelRenderer(this, 66, 0);
		Head.addBox(0F, 0F, 0F, 6, 5, 4);
		Head.setRotationPoint(-3F, 3F, -1F);
		Head.setTextureSize(128, 64);
		Head.mirror = true;
		setRotation(Head, 0F, 0F, 0F);
		WingConnection = new ModelRenderer(this, 0, 25);
		WingConnection.addBox(0F, 0F, 0F, 2, 3, 3);
		WingConnection.setRotationPoint(-1F, 13F, 3F);
		WingConnection.setTextureSize(128, 64);
		WingConnection.mirror = true;
		setRotation(WingConnection, 0F, 0F, 0F);
		WingPart1 = new ModelRenderer(this, 0, 31);
		WingPart1.addBox(0F, 0F, 0F, 6, 4, 1);
		WingPart1.setRotationPoint(-3F, 12F, 5F);
		WingPart1.setTextureSize(128, 64);
		WingPart1.mirror = true;
		setRotation(WingPart1, 0F, 0F, 0F);
		WingPart2 = new ModelRenderer(this, 0, 36);
		WingPart2.addBox(0F, 0F, 0F, 3, 4, 1);
		WingPart2.setRotationPoint(-4F, 11F, 5F);
		WingPart2.setTextureSize(128, 64);
		WingPart2.mirror = true;
		setRotation(WingPart2, 0F, 0F, 0F);
		WingPart3 = new ModelRenderer(this, 0, 36);
		WingPart3.addBox(0F, 0F, 0F, 3, 4, 1);
		WingPart3.setRotationPoint(-5F, 10F, 5F);
		WingPart3.setTextureSize(128, 64);
		WingPart3.mirror = true;
		setRotation(WingPart3, 0F, 0F, 0F);
		WingPart4 = new ModelRenderer(this, 0, 36);
		WingPart4.addBox(0F, 0F, 0F, 3, 4, 1);
		WingPart4.setRotationPoint(1F, 11F, 5F);
		WingPart4.setTextureSize(128, 64);
		WingPart4.mirror = true;
		setRotation(WingPart4, 0F, 0F, 0F);
		WingPart5 = new ModelRenderer(this, 0, 41);
		WingPart5.addBox(0F, 0F, 0F, 3, 2, 1);
		WingPart5.setRotationPoint(-6F, 10F, 5F);
		WingPart5.setTextureSize(128, 64);
		WingPart5.mirror = true;
		setRotation(WingPart5, 0F, 0F, 0F);
		WingPart6 = new ModelRenderer(this, 0, 36);
		WingPart6.addBox(0F, 0F, 0F, 3, 4, 1);
		WingPart6.setRotationPoint(2F, 10F, 5F);
		WingPart6.setTextureSize(128, 64);
		WingPart6.mirror = true;
		setRotation(WingPart6, 0F, 0F, 0F);
		WingPart7 = new ModelRenderer(this, 0, 41);
		WingPart7.addBox(0F, 0F, 0F, 3, 2, 1);
		WingPart7.setRotationPoint(3F, 10F, 5F);
		WingPart7.setTextureSize(128, 64);
		WingPart7.mirror = true;
		setRotation(WingPart7, 0F, 0F, 0F);
		TailFront = new ModelRenderer(this, 0, 50);
		TailFront.addBox(0F, 0F, 0F, 3, 1, 1);
		TailFront.setRotationPoint(-2F, 18F, 7F);
		TailFront.setTextureSize(128, 64);
		TailFront.mirror = true;
		setRotation(TailFront, 0F, 0F, 0F);
		TailBack = new ModelRenderer(this, 0, 44);
		TailBack.addBox(0F, 0F, 0F, 1, 1, 5);
		TailBack.setRotationPoint(0F, 18F, 3F);
		TailBack.setTextureSize(128, 64);
		TailBack.mirror = true;
		setRotation(TailBack, 0F, 0F, 0F);
		TailMiddle = new ModelRenderer(this, 0, 52);
		TailMiddle.addBox(0F, 0F, 0F, 1, 1, 3);
		TailMiddle.setRotationPoint(-2F, 18F, 7F);
		TailMiddle.setTextureSize(128, 64);
		TailMiddle.mirror = true;
		setRotation(TailMiddle, 0F, 0F, 0F);
		Arm1 = new ModelRenderer(this, 0, 15);
		Arm1.addBox(0F, 0F, 0F, 2, 2, 3);
		Arm1.setRotationPoint(5F, 11F, -2F);
		Arm1.setTextureSize(128, 64);
		Arm1.mirror = true;
		setRotation(Arm1, 0F, 0F, 0F);
		HandPart1 = new ModelRenderer(this, 100, 0);
		HandPart1.addBox(0F, 0F, 0F, 2, 2, 1);
		HandPart1.setRotationPoint(5F, 11F, -3F);
		HandPart1.setTextureSize(128, 64);
		HandPart1.mirror = true;
		setRotation(HandPart1, 0F, 0F, 0F);
		Ear1 = new ModelRenderer(this, 110, 0);
		Ear1.addBox(0F, 0F, 0F, 1, 2, 2);
		Ear1.setRotationPoint(-4F, 4F, 0F);
		Ear1.setTextureSize(128, 64);
		Ear1.mirror = true;
		setRotation(Ear1, 0F, 0F, 0F);
		Ear1 = new ModelRenderer(this, 110, 0);
		Ear1.addBox(0F, 0F, 0F, 1, 2, 2);
		Ear1.setRotationPoint(3F, 4F, 0F);
		Ear1.setTextureSize(128, 64);
		Ear1.mirror = true;
		setRotation(Ear1, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Foot1.render(f5);
		Foot2.render(f5);
		Leg1.render(f5);
		Leg2.render(f5);
		TorsoMain.render(f5);
		LegConnection1.render(f5);
		LegConnection2.render(f5);
		TorsoFront.render(f5);
		ArmConnection1.render(f5);
		ArmConnection2.render(f5);
		HandPart2.render(f5);
		Arm2.render(f5);
		Hand1.render(f5);
		Hand2.render(f5);
		Neck.render(f5);
		Banana.render(f5);
		Head.render(f5);
		WingConnection.render(f5);
		WingPart1.render(f5);
		WingPart2.render(f5);
		WingPart3.render(f5);
		WingPart4.render(f5);
		WingPart5.render(f5);
		WingPart6.render(f5);
		WingPart7.render(f5);
		TailFront.render(f5);
		TailBack.render(f5);
		TailMiddle.render(f5);
		Arm1.render(f5);
		HandPart1.render(f5);
		Ear1.render(f5);
		Ear1.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
